Modify media format labels
sul-dlss/vt-arclight pull request #322
Opened 2022-12-01 19:52 UTC by marlo-longley

2022-12-02 02:13 UTC, jcoyne requested changes
Can you add a request and/or a component test that shows these facets and component fields are correctly rendered?

2022-12-05 20:45 UTC, marlo-longley commented
@jcoyne this now reflects the tests and changes we looked at.

2022-12-05 21:14 UTC, jcoyne requested changes
I think we're still missing a test for the show page that indicates the labels are going through the new helper method.

2022-12-05 22:37 UTC, jcoyne approved these changes

2022-12-05 22:37 UTC, merged