Implement search with document feature
sul-dlss/vt-arclight pull request #451
Opened 2023-01-09 22:33 UTC by thatbudakguy

This borrows Exhibits' implementation and creates a link to open
the document with a search active in the embed viewer.

Also adds a small feature test for full text searching.

Closes #155

2023-01-10 15:35 UTC, jcoyne requested changes

2023-01-10 15:37 UTC, jcoyne requested changes

2023-01-10 15:37 UTC, jcoyne commented on spec/features/full_text_spec.rb
> +    expect(page).to have_link 'Search for "rosebud" in document text'
Can you move this to a Component test?  That will run much faster than a feature test. I'm not sure there's anything about this that requires javascript.

2023-01-10 18:23 UTC, thatbudakguy commented on app/components/oembed_viewer_component.rb
> +      arclight_oembed_search: params[:search]
I have no idea, I thought it was a magic global of some kind accessible in helpers & components. Exhibits used it to check what was set in the querystring, which seems to be what it does.

2023-01-10 18:26 UTC, thatbudakguy commented on spec/features/full_text_spec.rb
> +    expect(page).to have_link 'Search for "rosebud" in document text'
I can do that, but I'd need to pair with you to understand how to set it up — most of our component tests in VT are just placeholders, and I don't fully understand the logic in the ones that aren't

2023-01-10 20:04 UTC, jcoyne commented on spec/features/full_text_spec.rb
> +    expect(page).to have_link 'Search for "rosebud" in document text'
A presenter is a object that wraps a model that holds some presentation logic.  It's the ViewModel in the view-model-viewmodel pattern https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel

2023-01-18 16:00 UTC, jcoyne requested changes

2023-01-18 16:00 UTC, jcoyne commented on Gemfile.lock
> -    actioncable (7.0.4)
Why did this get in this PR? I don't see why a `bundle update` was necessary.

2023-01-18 16:00 UTC, jcoyne commented on spec/features/full_text_spec.rb
> +    expect(page).to have_link 'Search for "rosebud" in document text'
Can this be folded into the test on line 27 or omitted entirely (since there is a component test)?  Feature tests are slow, so we should be conservative about how many we need.

2023-01-18 17:58 UTC, marlo-longley commented
@thatbudakguy thanks for all your work on this. When running this branch locally, I'm not sure I'm seeing the intended functionality. When I click on a link in search (such as -- Search for "court" in document text), it links me to page 1 of the Mirador document, with nothing highlighted that I can see. Maybe we can link up to make sure I'm using it as intended before moving forward.

2023-01-18 19:24 UTC, thatbudakguy commented on Gemfile.lock
> -    actioncable (7.0.4)
Oh, some things failed after I rebased, so I think I can to `bundle update` to run tests....I'll try and get rid of it

2023-01-18 20:38 UTC, thatbudakguy commented
@marlo-longley give it another shot; I renamed some params as part of refactoring the tests. should be fixed now

2023-01-18 21:44 UTC, marlo-longley approved these changes

2023-01-19 01:04 UTC, jcoyne approved these changes

2023-01-19 01:04 UTC, merged