Spell out the indexing process in README
sul-dlss/vt-arclight pull request #460
Opened 2023-01-11 17:48 UTC by marlo-longley

2023-01-11 18:41 UTC, jcoyne requested changes

2023-01-11 18:41 UTC, jcoyne commented on README.md
> +SOLR_URL=http://sul-solr.stanford.edu/solr/nta-arclight-stage/ RAILS_ENV=production bundle exec rake vt:index
```suggestion
cap stage ssh
SOLR_URL=http://sul-solr.stanford.edu/solr/nta-arclight-stage/  RAILS_ENV=production bin/rails arclight:destroy_index_docs tmp:cache:clear vt:index
```

2023-01-11 21:47 UTC, thatbudakguy approved these changes

2023-01-12 13:45 UTC, jcoyne approved these changes

2023-01-12 13:45 UTC, merged