Add info tooltip to EAD download section
sul-dlss/vt-arclight pull request #521
Opened 2023-02-01 22:56 UTC by marlo-longley

2023-02-02 18:32 UTC, thatbudakguy approved these changes

2023-02-02 18:32 UTC, thatbudakguy commented on app/components/document_download_component.rb
> +    icon.html_safe # rubocop:disable Rails/OutputSafety
I think you can just say `sanitize icon` instead to make rubocop happy

2023-02-02 19:16 UTC, jcoyne requested changes

2023-02-02 19:16 UTC, jcoyne commented on app/components/document_download_component.rb
> +  def info_icon
```suggestion
  // From https://icons.getbootstrap.com/icons/question-circle-fill/
  def info_icon
```

2023-02-02 20:18 UTC, marlo-longley commented on app/components/document_download_component.rb
> +    icon.html_safe # rubocop:disable Rails/OutputSafety
@thatbudakguy do you mean in the view file?

2023-02-02 21:37 UTC, marlo-longley commented on app/components/document_download_component.rb
> +  def info_icon
done!

2023-02-03 00:12 UTC, thatbudakguy commented on app/components/document_download_component.rb
> +    icon.html_safe # rubocop:disable Rails/OutputSafety
no, I think `sanitize` is available as a method here too — if `sanitize icon` doesn't work, @jcoyne might know

2023-02-06 22:20 UTC, merged