edits to the descriptive text on VT landing page
sul-dlss/vt-arclight pull request #597
Opened 2023-11-21 18:50 UTC by laurensorensen

2023-11-21 19:20 UTC, corylown requested changes
@laurensorensen let me know if you want to pair on getting this pull request to pass the build/test so we can merge it.

2023-11-21 19:20 UTC, corylown commented on config/locales/en.yml
> +</ul> are included for browsing and searching in the Spotlight platform. For searching this particular platform, please refer to the <a href="https://exhibits.stanford.edu/virtual-tribunals/about/how
@laurensorensen this proposed change removes the line breaks so the app can load the yml file.
```suggestion
            exhibit_description_html: <p>At present, Virtual Tribunals collections are hosted on two different platforms. The <a href="http://exhibits.stanford.edu/virtual-tribunals">Virtual Tribunals exhibit</a> provides access through the open source <a href="https://library.stanford.edu/spotlight-digital-exhibits">Spotlight</a> software. Trial records from <ul><li><a href="https://exhibits.stanford.edu/virtual-tribunals/feature/world-war-ii-u-s-army-courts-europe">World War II U.S. Army Courts, Europe</a></li><li><a href="https://exhibits.stanford.edu/virtual-tribunals/feature/world-war-ii-u-s-army-courts-asia-pacific">World War II U.S. Army Courts, Asia-Pacific</a></li><li><a href="https://exhibits.stanford.edu/virtual-tribunals/feature/special-panels-for-serious-crimes-east-timor-spsc">Special Panels for Serious Crimes in East Timor (SPSC)</a></li><li><a href="https://exhibits.stanford.edu/virtual-tribunals/feature/taube-archive-of-the-international-military-tribunal-imt-at-nuremberg-1945-46">Digitized static documents from the Nuremberg Trial Archives</a></li></ul> are included for browsing and searching in the Spotlight platform. For searching this particular platform, please refer to the <a href="https://exhibits.stanford.edu/virtual-tribunals/about/how-to-search-the-documents">How to Search the Collections page</a> for tips on searching using keywords and facets, and how to search across collections within Spotlight.</p>
```

2023-11-22 20:15 UTC, laurensorensen commented on config/locales/en.yml
> +</ul> are included for browsing and searching in the Spotlight platform. For searching this particular platform, please refer to the <a href="https://exhibits.stanford.edu/virtual-tribunals/about/how
Thanks for doing that! I'm realizing that I jumped the gun a little bit on this. We're releasing the two new collections on Dec 10 (though they are technically live now for people on VT team to review). So I'm going to put on my calendar to come back to this on December 5. Does that sound ok?

2023-12-07 15:53 UTC, closed without merging

2023-12-07 15:53 UTC, corylown commented on config/locales/en.yml
> +</ul> are included for browsing and searching in the Spotlight platform. For searching this particular platform, please refer to the <a href="https://exhibits.stanford.edu/virtual-tribunals/about/how
@laurensorensen I put these changes up in a separate pull request, see: https://github.com/sul-dlss/vt-arclight/pull/601